DROP TABLE IF EXISTS abbonati;
CREATE TABLE abbonati (
	id_account VARCHAR(25) NOT NULL,
	id_canale VARCHAR(25) NOT NULL,
	costoAbbonamento DECIMAL NOT NULL,
	PRIMARY KEY (id_account,id_canale),
	FOREIGN KEY (id_account) REFERENCES account(username) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (id_canale) REFERENCES canale(nome) ON UPDATE CASCADE ON DELETE CASCADE
);

insert into abbonati (id_account, id_canale, costoAbbonamento) values
('dyurshev1l', 'ipettisall1', 4),
('jfennaf', 'emuckian2', 4),
('jbruckstein17', 'scosgrive3', 20),
('jbruckstein17', 'bsear4', 4),
('smatzkaitis8', 'ecove5', 8),
('bcarcassa', 'dlarmor6', 4),
('akersting1z', 'selvins7', 2),
('dhollingshead26', 'jgreenig8', 4),
('smatzkaitis8', 'ezuker9', 20),
('mpopescue', 'esainthilla', 20),
('nmcconnell1y', 'tgarshoreb', 4),
('nmcconnell1y', 'itoughc', 4),
('kcorse7', 'rjeckelld', 8),
('wcheer2d', 'byurocjhine', 20),
('lonraet1g', 'sdongatef',20),
('dyurshev1l', 'dgumeyg', 8),
('slequesne2l', 'wromushkinh', 8),
('lonraet1g', 'vjavesi', 4),
('dyurshev1l', 'mbladesmithj', 8),
('ydonovin5', 'oriselyk', 20),
('ydonovin5', 'xiddinsl', 4),
('lbarhem1c', 'mtruterm', 4),
('slequesne2l', 'qmeaghern', 8),
('ewestern11', 'estebbingso', 4),
('zdimbylowp', 'emizzip', 8),
('sambrosettir', 'hfarnq', 20),
('gwadlyt', 'abrandhams', 4),
('zdimbylowp', 'rgarstanr', 8),
('sambrosettir', 'ipettisall1', 20),
('bcarcassa', 'emuckian2', 8),
('dshelmerdine1v', 'scosgrive3', 8),
('ewestern11', 'bsear4', 4),
('sambrosettir', 'ecove5', 8),
('gwadlyt', 'dlarmor6', 4),
('mpopescue', 'selvins7', 20),
('ewestern11', 'jgreenig8', 4),
('zdimbylowp', 'ezuker9', 20),
('ewestern11', 'esainthilla', 8),
('mpopescue', 'tgarshoreb', 20),
('ydonovin5', 'itoughc', 8);