DROP TABLE IF EXISTS clip;
CREATE TABLE clip (
    id_clip INT NOT NULL,
	id_canale VARCHAR(25) NOT NULL,
    titolo VARCHAR(25) NOT NULL,
	durata  TIMESTAMP NOT NULL,
	id_account VARCHAR(25) NOT NULL,
	visualizzazioni INT NOT NULL,
	PRIMARY KEY (id_clip),
	FOREIGN KEY (id_canale) REFERENCES canale(nome) ON UPDATE CASCADE ON DELETE CASCADE
	FOREIGN KEY (id_account) REFERENCES account(username) ON UPDATE CASCADE ON DELETE CASCADE
);

