DROP TABLE IF EXISTS modera;
CREATE TABLE modera (
	id_account VARCHAR(25) NOT NULL,
	id_canale VARCHAR(25) NOT NULL,
	PRIMARY KEY (id_account,id_canale),
	FOREIGN KEY (id_account) REFERENCES account(username) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (id_canale) REFERENCES canale(nome) ON UPDATE CASCADE ON DELETE CASCADE
);
insert into modera (id_account, id_canale) values
('dsherebrook0', 'njehan5'),
('tlepiscopi2', 'jmetzel1d'),
('aderkes4', 'rstaveley32'),
('dcoburn6', 'kquince3a'),
('hrobathon9', 'klapwood2l'),
('tyongj', 'gtrounce19'),
('bdewettk', 'jberney2o'),
('jpatriao', 'achalcraft2x'),
('bkinchinq', 'bspadazzis'),
('mupstonv', 'jbamb2r'),
('dmargaretx', 'jbamb2r'),
('bsaye10', 'fdoxey38'),
('eballendine12', 'dparkhouse1'),
('kwindaybank13', 'cpayn3j'),
('fshoard15', 'dwince2e'),
('mwinear16', 'dlarwell16'),
('kcottill18', 'alafayette14'),
('ncoventon19', 'bspadazzis'),
('ebresnahan1b', 'mlewknor26'),
('mmarcinkowski1f', 'qolekhov3'),
('abrandel1j', 'ljuckes1g'),
('kgilford1k', 'samberc'),
('mburdas1p', 'lcarnilian1z'),
('thardi1q', 'jperham1x'),
('clefrank1r', 'jloving17'),
('wwildes1s', 'acicconek'),
('kaudritt1t', 'eandrioli18'),
('ddorsett1w', 'tlealleo'),
('rgent1x', 'fkretschmer2i'),
('imulhill28', 'zdomengetw'),
('mtreweke29', 'jbamb2r'),
('akersaw2a', 'jperham1x'),
('begar2e', 'ewaterdrinker1j'),
('korhrt2f', 'bpringer2b'),
('pvigours2i', 'tloxdale1t'),
('jskokoe2r', 'dparkhouse1'),
('dsherebrook0', 'ohallifax1o'),
('tlepiscopi2', 'nbrent2c'),
('aderkes4', 'csorensen10'),
('dcoburn6', 'gtrounce19'),
('hrobathon9', 'rriddiough36'),
('tyongj', 'fgladman1a'),
('bdewettk', 'kgarbutt3d'),
('jpatriao', 'lgocher27'),
('bkinchinq', 'rhanburybrownl'),
('mupstonv', 'rhallatt37'),
('dmargaretx', 'rstaveley32'),
('bsaye10', 'aderuel21'),
('eballendine12', 'jgamlin1v'),
('kwindaybank13', 'dparkhouse1'),
('fshoard15', 'bspadazzis'),
('mwinear16', 'ddraisey1u'),
('kcottill18', 'vbrownsey20'),
('ncoventon19', 'jgamlin1v'),
('ebresnahan1b', 'nfansy2t'),
('mmarcinkowski1f', 'dedmondson1c'),
('abrandel1j', 'astroband29'),
('kgilford1k', 'vbrownsey20'),
('mburdas1p', 'rkreberf'),
('thardi1q', 'astroband29');